log_level = "warn"
database_host = "localhost"
database_port = "5432"
database_name = "rustwebdev"
port = 8080
POSTGRES_USER=user
POSTGRES_PASSWORD=password
POSTGRES_DB=rustwebdev
POSTGRES_HOST=localhost
POSTGRES_PORT=5432